language: c
env:
  - PLATFORM=linux
  - PLATFORM=windows
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -f mingw-w64 gcc-mingw-w64 gcc-mingw-w64-i686 gcc-mingw-w64-x86-64
script:
  - make $PLATFORM
