language: c
env:
  - PLATFORM=linux
  - PLATFORM=windows
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -f mingw-w64 binutils-mingw-w64-i686 binutils-mingw-w64-x86-64
script:
  - make $PLATFORM -e
